# Generated by Django 4.2.4 on 2023-08-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created',)},
        ),
    ]
