# Generated by Django 4.2.4 on 2023-08-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='articles',
        ),
    ]
