# Generated by Django 4.2.4 on 2023-08-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_rename_article_comment_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
    ]
