# Generated by Django 4.2.4 on 2023-08-17 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 3, 34, 40, 694990)),
        ),
    ]
